"""add athlete checkin

Revision ID: 7a8a0828fece
Revises: 9f0940493a9b

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a8a0828fece"
down_revision: Union[str, None] = "9f0940493a9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athlete_checkin",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=True),
        sa.Column("stress_rating", sa.Integer(), nullable=False),
        sa.Column("energy_rating", sa.Integer(), nullable=False),
        sa.Column("focus_rating", sa.Integer(), nullable=False),
        sa.Column("confidence_rating", sa.Integer(), nullable=False),
        sa.Column("soreness_rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("confidence_rating BETWEEN 1 AND 10", name="ck_athlete_checkin_confidence"),
        sa.CheckConstraint("energy_rating BETWEEN 1 AND 10", name="ck_athlete_checkin_energy"),
        sa.CheckConstraint("focus_rating BETWEEN 1 AND 10", name="ck_athlete_checkin_focus"),
        sa.CheckConstraint("soreness_rating BETWEEN 1 AND 10", name="ck_athlete_checkin_soreness"),
        sa.CheckConstraint("stress_rating BETWEEN 1 AND 10", name="ck_athlete_checkin_stress"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("athlete_checkin")
    # ### end Alembic commands ###
