"""add performance and athlete daily feature tables

Revision ID: 38a9178842f2
Revises: 2c93ee51b44c

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38a9178842f2"
down_revision: Union[str, None] = "2c93ee51b44c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "performance_metric_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport", sa.String(length=64), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sport", "metric_key", name="uq_sport_metric_key"),
    )
    op.create_table(
        "athlete_daily_feature",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("recovery_score", sa.Float(), nullable=True),
        sa.Column("strain_score", sa.Float(), nullable=True),
        sa.Column("hrv_rmssd_ms", sa.Float(), nullable=True),
        sa.Column("resting_heart_rate_bpm", sa.Float(), nullable=True),
        sa.Column("sleep_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("sleep_efficiency_percentage", sa.Float(), nullable=True),
        sa.Column("hrv_baseline_7d", sa.Float(), nullable=True),
        sa.Column("hrv_baseline_28d", sa.Float(), nullable=True),
        sa.Column("resting_hr_baseline_7d", sa.Float(), nullable=True),
        sa.Column("resting_hr_baseline_28d", sa.Float(), nullable=True),
        sa.Column("sleep_duration_baseline_7d", sa.Integer(), nullable=True),
        sa.Column("strain_acute_7d", sa.Float(), nullable=True),
        sa.Column("strain_chronic_28d", sa.Float(), nullable=True),
        sa.Column("source_coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feature_version", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "local_date", name="uq_athlete_daily_feature_user_date"),
    )
    op.create_index(op.f("ix_athlete_daily_feature_user_id"), "athlete_daily_feature", ["user_id"], unique=False)
    op.create_table(
        "performance_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("sport", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_perf_event_user_sport_time", "performance_event", ["user_id", "sport", "started_at"], unique=False
    )
    op.create_index("ix_perf_event_user_time", "performance_event", ["user_id", "started_at"], unique=False)
    op.create_table(
        "performance_metric_value",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("performance_event_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("text_value", sa.String(length=255), nullable=True),
        sa.Column("boolean_value", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["metric_definition_id"], ["performance_metric_definition.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["performance_event_id"], ["performance_event.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_event_id", "metric_definition_id", name="uq_event_metric"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("performance_metric_value")
    op.drop_index("ix_perf_event_user_time", table_name="performance_event")
    op.drop_index("ix_perf_event_user_sport_time", table_name="performance_event")
    op.drop_table("performance_event")
    op.drop_index(op.f("ix_athlete_daily_feature_user_id"), table_name="athlete_daily_feature")
    op.drop_table("athlete_daily_feature")
    op.drop_table("performance_metric_definition")
    # ### end Alembic commands ###
