"""add performance event link to athlete checkin

Revision ID: 32f41ea801e9
Revises: 38a9178842f2

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32f41ea801e9"
down_revision: Union[str, None] = "38a9178842f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("athlete_checkin", sa.Column("performance_event_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "athlete_checkin", "performance_event", ["performance_event_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "athlete_checkin", type_="foreignkey")
    op.drop_column("athlete_checkin", "performance_event_id")
    # ### end Alembic commands ###
